-- V2: Ingredient

CREATE EXTENSION IF NOT EXISTS citext;

       CREATE TABLE ingredient (
           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
           name CITEXT NOT NULL,
           category TEXT NULL,
           created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
           updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );

ALTER TABLE ingredient
    ADD CONSTRAINT uq_ingredient_name UNIQUE (name);