CREATE TABLE recipe (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE recipe_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id BIGINT NOT NULL  REFERENCES recipe(id) ON DELETE CASCADE,
    ingredient_id BIGINT NOT NULL REFERENCES ingredient(id),
    amount NUMERIC(12,3) NOT NULL,
    unit TEXT NOT NULL,
    note TEXT NULL
);

CREATE INDEX ix_recipe_item_recipe_id ON recipe_item(recipe_id);