CREATE TABLE weekly_menu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    week_start_Date DATE NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE weekly_menu_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    weekly_menu_id BIGINT NOT NULL REFERENCES weekly_menu(id) ON DELETE CASCADE,
    day_of_week SMALLINT NOT NULL CHECK ( day_of_week BETWEEN 1 AND 7),
    recipe_id BIGINT NOT NULL REFERENCES recipe(id),
    note TEXT NULL
);

ALTER TABLE weekly_menu_entry
 ADD CONSTRAINT uq_weekly_menu_day UNIQUE (weekly_menu_id, day_of_week);

CREATE INDEX ix_weekly_menu_entry_menu_id ON weekly_menu_entry(weekly_menu_id);